config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  root to: 'home#index'

  devise_for(:spree_user, {
    class_name: 'Spree::User',
    controllers: {
      sessions: 'spree/user_sessions',
      registrations: 'spree/user_registrations',
      passwords: 'spree/user_passwords',
      confirmations: 'spree/user_confirmations'
    },
    skip: [:unlocks, :omniauth_callbacks],
    path_names: { sign_out: 'logout' },
    path_prefix: :user,
    router_name: :spree
  })

  resources :users, only: [:edit, :update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  resources :products, only: [:index, :show]

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  # non-restful checkout stuff
  get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
  put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration
  patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
  get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  get '/checkout', to: 'checkout#edit', as: :checkout

  get '/orders/populate', to: 'orders#populate_redirect'
  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, except: [:index, :new, :create, :destroy] do
    post :populate, on: :collection
    resources :coupon_codes, only: :create
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link
end
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/spree/checkout_controller.rb
# frozen_string_literal: true

module Spree
  # This is somewhat contrary to standard REST convention since there is not
  # actually a Checkout object. There's enough distinct logic specific to
  # checkout which has nothing to do with updating an order that this approach
  # is warranted.
  class CheckoutController < Spree::StoreController
    before_action :load_order
    around_action :lock_order

    before_action :ensure_order_is_not_skipping_states
    before_action :ensure_order_not_completed
    before_action :ensure_checkout_allowed
    before_action :ensure_sufficient_stock_lines
    before_action :ensure_valid_state

    before_action :associate_user
    before_action :check_registration, except: [:registration, :update_registration]
    before_action :check_authorization

    before_action :setup_for_current_state, only: [:edit, :update]

    helper 'spree/orders'

    rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error
    rescue_from Spree::Order::InsufficientStock, with: :insufficient_stock_error

    # Updates the order and advances to the next state (when possible.)
    def update
      if update_order

        assign_temp_address

        unless transition_forward
          redirect_on_failure
          return
        end

        if @order.completed?
          finalize_order
        else
          send_to_next_state
        end

      else
        render :edit
      end
    end

    def registration
      @user = Spree::User.new
    end

    def update_registration
      if params[:order][:email] =~ Devise.email_regexp && current_order.update(email: params[:order][:email])
        redirect_to spree.checkout_path
      else
        flash[:registration_error] = t(:email_is_invalid, scope: [:errors, :messages])
        @user = Spree::User.new
        render 'registration'
      end
    end

    private

    def update_order
      OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
    end

    def assign_temp_address
      @order.temporary_address = !params[:save_user_address]
    end

    def redirect_on_failure
      flash[:error] = @order.errors.full_messages.join("\n")
      redirect_to(checkout_state_path(@order.state))
    end

    def transition_forward
      if @order.can_complete?
        @order.complete
      else
        @order.next
      end
    end

    def finalize_order
      @current_order = nil
      set_successful_flash_notice
      redirect_to completion_route
    end

    def set_successful_flash_notice
      flash.notice = t('spree.order_processed_successfully')
      flash['order_completed'] = true
    end

    def send_to_next_state
      redirect_to checkout_state_path(@order.state)
    end

    def update_params
      case params[:state].to_sym
      when :address
        massaged_params.require(:order).permit(
          permitted_checkout_address_attributes
        )
      when :delivery
        massaged_params.require(:order).permit(
          permitted_checkout_delivery_attributes
        )
      when :payment
        massaged_params.require(:order).permit(
          permitted_checkout_payment_attributes
        )
      else
        massaged_params.fetch(:order, {}).permit(
          permitted_checkout_confirm_attributes
        )
      end
    end

    def massaged_params
      massaged_params = params.deep_dup

      move_payment_source_into_payments_attributes(massaged_params)
      move_wallet_payment_source_id_into_payments_attributes(massaged_params)
      set_payment_parameters_amount(massaged_params, @order)

      massaged_params
    end

    def ensure_valid_state
      unless skip_state_validation?
        if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
           (!params[:state] && !@order.has_checkout_step?(@order.state))
          @order.state = 'cart'
          redirect_to checkout_state_path(@order.checkout_steps.first)
        end
      end

      # Fix for https://github.com/spree/spree/issues/4117
      # If confirmation of payment fails, redirect back to payment screen
      if params[:state] == "confirm" && @order.payment_required? && @order.payments.valid.empty?
        flash.keep
        redirect_to checkout_state_path("payment")
      end
    end

    def load_order
      @order = current_order
      redirect_to(spree.cart_path) && return unless @order
    end

    # Allow the customer to only go back or stay on the current state
    # when trying to change it via params[:state]. It's not allowed to
    # jump forward and skip states (unless #skip_state_validation? is
    # truthy).
    def ensure_order_is_not_skipping_states
      if params[:state]
        redirect_to checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
        @order.state = params[:state]
      end
    end

    def ensure_checkout_allowed
      unless @order.checkout_allowed?
        redirect_to spree.cart_path
      end
    end

    def ensure_order_not_completed
      redirect_to spree.cart_path if @order.completed?
    end

    def ensure_sufficient_stock_lines
      if @order.insufficient_stock_lines.present?
        out_of_stock_items = @order.insufficient_stock_lines.collect(&:name).to_sentence
        flash[:error] = t('spree.inventory_error_flash_for_insufficient_quantity', names: out_of_stock_items)
        redirect_to spree.cart_path
      end
    end

    def setup_for_current_state
      method_name = :"before_#{@order.state}"
      send(method_name) if respond_to?(method_name, true)
    end

    def before_address
      @order.assign_default_user_addresses
      # If the user has a default address, the previous method call takes care
      # of setting that; but if he doesn't, we need to build an empty one here
      @order.bill_address ||= Spree::Address.build_default
      @order.ship_address ||= Spree::Address.build_default if @order.checkout_steps.include?('delivery')
    end

    def before_delivery
      return if params[:order].present?

      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
    end

    def before_payment
      if @order.checkout_steps.include? "delivery"
        packages = @order.shipments.map(&:to_package)
        @differentiator = Spree::Stock::Differentiator.new(@order, packages)
        @differentiator.missing.each do |variant, quantity|
          @order.contents.remove(variant, quantity)
        end
      end

      if spree_current_user && spree_current_user.respond_to?(:wallet)
        @wallet_payment_sources = spree_current_user.wallet.wallet_payment_sources
        @default_wallet_payment_source = @wallet_payment_sources.detect(&:default) ||
                                         @wallet_payment_sources.first
      end
    end

    def rescue_from_spree_gateway_error(exception)
      flash.now[:error] = t('spree.spree_gateway_error_flash_for_checkout')
      @order.errors.add(:base, exception.message)
      render :edit
    end

    def insufficient_stock_error
      packages = @order.shipments.map(&:to_package)
      if packages.empty?
        flash[:error] = I18n.t('spree.insufficient_stock_for_order')
        redirect_to cart_path
      else
        availability_validator = Spree::Stock::AvailabilityValidator.new
        unavailable_items = @order.line_items.reject { |line_item| availability_validator.validate(line_item) }
        if unavailable_items.any?
          item_names = unavailable_items.map(&:name).to_sentence
          flash[:error] = t('spree.inventory_error_flash_for_insufficient_shipment_quantity', unavailable_items: item_names)
          @order.restart_checkout_flow
          redirect_to spree.checkout_state_path(@order.state)
        end
      end
    end

    def order_params
      params.
        fetch(:order, {}).
        permit(:email)
    end

    def skip_state_validation?
      %w(registration update_registration).include?(params[:action])
    end

    def check_authorization
      authorize!(:edit, current_order, cookies.signed[:guest_token])
    end

    # Introduces a registration step whenever the +registration_step+ preference is true.
    def check_registration
      return unless registration_required?

      store_location
      redirect_to spree.checkout_registration_path
    end

    def registration_required?
      Spree::Auth::Config[:registration_step] &&
        !already_registered?
    end

    def already_registered?
      spree_current_user || guest_authenticated?
    end

    def guest_authenticated?
      current_order&.email.present? &&
        Spree::Config[:allow_guest_checkout]
    end

    # Overrides the equivalent method defined in Spree::Core.  This variation of the method will ensure that users
    # are redirected to the tokenized order url unless authenticated as a registered user.
    def completion_route
      return spree.order_path(@order) if spree_current_user

      spree.token_order_path(@order, @order.guest_token)
    end
  end
end

app/controllers/spree/coupon_codes_controller.rb
# frozen_string_literal: true

module Spree
  class CouponCodesController < Spree::StoreController
    before_action :load_order, only: :create
    around_action :lock_order, only: :create

    def create
      authorize! :update, @order, cookies.signed[:guest_token]

      if params[:coupon_code].present?
        @order.coupon_code = params[:coupon_code]
        handler = PromotionHandler::Coupon.new(@order).apply

        respond_with(@order) do |format|
          format.html do
            if handler.successful?
              flash[:success] = handler.success
            else
              flash[:error] = handler.error
            end

            redirect_back fallback_location: cart_path
          end
        end
      end
    end

    private

    def load_order
      @order = current_order
    end
  end
end

app/controllers/spree/home_controller.rb
# frozen_string_literal: true

module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
    end
  end
end

app/controllers/spree/locale_controller.rb
# frozen_string_literal: true

module Spree
  class LocaleController < Spree::StoreController
    def set
      requested_locale = params[:switch_to_locale] || params[:locale]

      if locale_is_available?(requested_locale)
        I18n.locale = requested_locale
        session[set_user_language_locale_key] = requested_locale
        flash.notice = t('spree.locale_changed')
      else
        flash[:error] = t('spree.locale_not_changed')
      end

      redirect_to spree.root_path
    end

    private

    def locale_is_available?(locale)
      locale && Spree.i18n_available_locales.include?(locale.to_sym)
    end
  end
end

app/controllers/spree/products_controller.rb
# frozen_string_literal: true

module Spree
  class ProductsController < Spree::StoreController
    before_action :load_product, only: :show
    before_action :load_taxon, only: :index

    helper 'spree/taxons', 'spree/taxon_filters'

    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
    end

    def show
      @variants = @product.
        variants_including_master.
        display_includes.
        with_prices(current_pricing_options).
        includes([:option_values, :images])

      @product_properties = @product.product_properties.includes(:property)
      @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
    end

    private

    def accurate_title
      if @product
        @product.meta_title.blank? ? @product.name : @product.meta_title
      else
        super
      end
    end

    def load_product
      if spree_current_user.try(:has_spree_role?, "admin")
        @products = Spree::Product.with_discarded
      else
        @products = Spree::Product.available
      end
      @product = @products.friendly.find(params[:id])
    end

    def load_taxon
      @taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon].present?
    end
  end
end

app/controllers/spree/store_controller.rb
# frozen_string_literal: true

module Spree
  class StoreController < Spree::BaseController
    include Spree::Core::ControllerHelpers::Pricing
    include Spree::Core::ControllerHelpers::Order
    include SolidusStarterFrontend::Taxonomies

    def unauthorized
      render 'spree/shared/auth/unauthorized', layout: Spree::Config[:layout], status: 401
    end

    def cart_link
      render partial: 'spree/shared/cart/link_to_cart'
      fresh_when(current_order, template: 'spree/shared/cart/_link_to_cart')
    end

    private

    def config_locale
      I18n.locale
    end

    def lock_order
      Spree::OrderMutex.with_lock!(@order) { yield }
    rescue Spree::OrderMutex::LockFailed
      flash[:error] = t('spree.order_mutex_error')
      redirect_to spree.cart_path
    end
  end
end

app/helpers/spree/orders_helper.rb
# frozen_string_literal: true

require 'truncate_html'
require 'app/helpers/truncate_html_helper'

module Spree
  module OrdersHelper
    include TruncateHtmlHelper

    def truncated_product_description(product)
      truncate_html(raw(product.description))
    end

    def order_just_completed?(order)
      flash[:order_completed] && order.present?
    end
  end
end

app/helpers/spree/product_options_helper.rb
# frozen_string_literal: true

module Spree
  module ProductOptionsHelper
    def product_variants_with_options(product)
      product.variants_and_option_values_for(current_pricing_options)
    end

    def sorted_option_values(variant)
      variant.option_values.sort_by { |value| value.option_type.position }.map(&:id)
    end

    def sorted_option_types(product)
      product.option_types.sort_by(&:position)
    end

    # move to model
    def option_values(product:, option_type:)
      product.variants.map do |variant|
        variant.option_values.find { |option_value| option_value.option_type_id == option_type.id }
      end.compact.uniq
    end
  end
end

app/helpers/spree/taxon_filters_helper.rb
# frozen_string_literal: true

require 'spree/core/product_filters'

module Spree
  module TaxonFiltersHelper
    def applicable_filters_for(_taxon)
      [:brand_filter, :price_filter].map do |filter_name|
        Spree::Core::ProductFilters.send(filter_name) if Spree::Core::ProductFilters.respond_to?(filter_name)
      end.compact
    end
  end
end

app/views/spree/products/_product-card.html.erb
<%
  base_class = "product-card".freeze

  # Optional props
  classes = local_assigns.fetch(:classes, [])

  # Classes
  class_names = classes.push(base_class).join(" ")

  url = spree.product_path(product, taxon_id: @taxon.try(:id))
  cached = @taxon.present? ?
    [I18n.locale, current_pricing_options, @taxon, product] :
    [I18n.locale, current_pricing_options, product]
  product_id = "product_#{product.id}"
%>

<% cache cached do %>
  <li class="<%= class_names %>" itemscope itemtype="http://schema.org/Product" id=<%= product_id %>>
    <article>
      <section class="product-card_image">
        <%= link_to render(ImageComponent.new(image: product.gallery.images.first, size: :small, itemprop: "image")), url, itemprop: 'url' %>
      </section>
      <header class="product-card_header">
        <h2>
          <%= link_to truncate(product.name, length: 50), url, class: 'info', itemprop: "name", title: product.name %>
        </h2>
      </header>
      <section class="product-card_price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
        <% if price = product.price_for_options(current_pricing_options)&.money %>
          <span class="price selling" itemprop="price" content="<%= price.to_d %>">
            <%= price.to_html %>
          </span>
        <% end %>
        <span itemprop="priceCurrency" content="<%= current_pricing_options.currency %>"></span>
      </section>
    </article>
  </li>
<% end %>

app/views/spree/products/_product_availability.html.erb
<%
  base_class = "product-availability".freeze

  # Optional props
  classes = local_assigns.fetch(:classes, [])

  # Classes
  class_names = classes.push(base_class).join(" ")
%>

<% if product.master.can_supply? %>
  <link itemprop="availability" href="http://schema.org/InStock" />
<% elsif product.variants.empty? %>
  <span
    class="<%= class_names %>"
    itemprop="availability"
    href="http://schema.org/OutOfStock"
  >
    <%= t('spree.out_of_stock') %>
  </span>
<% end %>

app/views/spree/products/_product_form.html.erb
<%
  schema_properties = {
    itemprop: 'offers',
    itemscope: true,
    itemtype: 'http://schema.org/Offer'
  }
%>

<%= form_for :order, url: populate_orders_path, html: schema_properties do |f| %>
  <% if product_variants_with_options(product).any? %>
    <div class="variant-container">
      <% sorted_option_types(product).each_with_index do |option_type, i| %>
        <div class="variant-selection">
          <%= render 'spree/products/product_selection/option_type', product: product, option_type: option_type, index: i %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= render 'product_variants', product: product %>

  <% if product.price %>
    <%= render 'product_submit', product: product %>
  <% else %>
    <div id="product-price">
      <p data-js="price" itemprop="price">
        <%= t('spree.product_not_available_in_this_currency') %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/spree/products/_product_header.html.erb
<header class="product-header">
  <h1 class="product-header__title" itemprop="name">
    <%= product.name %>
  </h1>

  <% if product.price_for_options(current_pricing_options)&.money and !product.price.nil? %>
    <h2 class="product-header__title" id="product-price">
      <%= content_tag(
        :span,
        display_price(product),
        itemprop: 'price',
        content: product.price_for_options(current_pricing_options)&.money.to_d,
        data: { js: 'price' }
      ) %>

      <%= content_tag(
        :span,
        nil,
        itemprop: 'priceCurrency',
        content: current_pricing_options.currency
      ) %>
    </h2>
  <% end %>
</header>

app/views/spree/products/_product_image.html.erb
<picture class="product-image">
  <%= render(ImageComponent.new(
    image: product.gallery.images.first,
    size: :product,
    itemprop: "image",
    data: { js: 'product-main-image' }
  )) %>
</picture>

app/views/spree/products/_product_info.html.erb
<div class="product-page__description">
  <h2 class="product-description__title">
    <%= t('description') %>
  </h2>

  <p class="product-description" itemprop="description">
    <%= product_description(product) rescue t('spree.product_has_no_description') %>
  </p>
</div>

app/views/spree/products/_product_promotions.html.erb
<% promotions = product.possible_promotions %>

<% if promotions.any? %>
  <section class="product-promotions">
    <h2><%= t('spree.promotions') %></h2>

    <% promotions.each do |promotion| %>
      <article>
        <header>
          <h3><%= promotion.name %></h3>
        </header>

        <p><%= promotion.description %></p>

        <% if promotion.products.any? %>
          <ul>
            <% promotion.products.each do |product| %>
              <li><%= link_to product.name, product_path(product) %></li>
            <% end %>
          </ul>
        <% end %>
      </article>
    <% end %>
  </section>
<% end %>

app/views/spree/products/_product_submit.html.erb
<div class="product-submit">
  <%= render 'product_availability', product: product %>

  <div class="horizontal-input-group">
    <div class="horizontal-input-group__input">
      <div class="text-input">
        <%= text_field_tag :quantity, 1, type: :number, min: 1 %>
      </div>
    </div>
    <div class="horizontal-input-group__action">
      <%= button_tag(
        t('spree.add_to_cart'),
        class: 'button-primary',
        id: 'add-to-cart-button'
      ) %>
    </div>
  </div>
</div>

app/views/spree/products/_product_taxons.html.erb
<% if !product.taxons.blank? %>
  <section class="product-taxons">
    <h2 class="product-taxons__title">
      <%= t('spree.look_for_similar_items') %>:
    </h2>

    <ul class="product-taxons__list">
      <% product.taxons.each do |taxon| %>
        <li>
          <%= link_to taxon.name, seo_url(taxon) %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/spree/products/_product_thumbnails.html.erb
<ul class="product-thumbnails">
  <% product.gallery.images.each do |image| %>
    <% next if image.viewable_id != product.master.id %>

    <%= content_tag(
      :li,
      class: 'product-thumbnails__all',
      data: { js: 'product-thumbnail', js_id: image.viewable_id }
    ) do %>
      <%= link_to(image_tag(image.url(:mini)), image.url(:product)) %>
    <% end %>
  <% end %>

  <% if product.has_variants? %>
    <% product.gallery.images.each do |image| %>
      <% next if image.viewable_id == product.master.id %>

      <%= content_tag(
        :li,
        class: 'product-thumbnails__variant',
        data: { js: 'variant-thumbnail', js_id: image.viewable_id }
      ) do %>
        <%= link_to(image_tag(image.url(:mini)), image.url(:product)) %>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/spree/products/_product_variants.html.erb
<%
  variants = product.variants_and_option_values_for(current_pricing_options)
%>

<% if variants.any? %>
  <section class="product-variants d-hide">
    <h2 class="product-variants__title">
      <%= t('spree.variants') %>
    </h2>

    <ul class="product-variants__list">
      <% variants.each_with_index do |variant, index| %>
        <li class='d-hide'>
          <%= radio_button_tag(
            'variant_id',
            variant.id,
            index == 0,
            "data-js" => 'variant-radio',
            "data-js_price" => variant.price_for_options(current_pricing_options)&.money.to_s,
            "data-option-value-ids" => sorted_option_values(variant).to_json,
            "data-target" => "variantOptions",
            "data-price" => variant.price_for_options(current_pricing_options)&.money&.to_html
          ) %>

          <%= label_tag "variant_id_#{ variant.id }" do %>
            <%= variant_options variant %>

            <% if variant_price variant %>
              <span class="price diff"><%= variant_price variant %></span>
            <% end %>

            <% unless variant.can_supply? %>
              <span class="out-of-stock"><%= t('spree.out_of_stock') %></span>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>
<% else %>
  <%= hidden_field_tag "variant_id", product.master.id %>
<% end %>

app/views/spree/products/_products-grid.html.erb
<%
  base_class = "products-grid".freeze

  # Optional props
  classes = local_assigns.fetch(:classes, [])

  # Classes
  class_names = classes.push(base_class).join(" ")
%>

<ul class="<%= class_names %>">
  <% products.each do |product| %>
    <%= render 'spree/products/product-card', product: product %>
  <% end %>
</ul>

app/views/spree/products/_products.html.erb
<%
  paginated_products = @searcher.retrieve_products if params.key?(:keywords)
  paginated_products ||= products
  no_products_found = products.empty?
%>

<% content_for :head do %>
  <% if paginated_products.respond_to?(:total_pages) %>
    <%= rel_next_prev_link_tags paginated_products %>
  <% end %>
<% end %>

<% if no_products_found %>
  <h2 class="products__results-title">
    <%= t('spree.no_products_found') %>
  </h2>
<% elsif params.key?(:keywords) %>
  <h1 class="products__results-title">
    <%= t('spree.search_results', keywords: h(params[:keywords])) %>
  </h1>
<% end %>

<% if !no_products_found %>
  <%= render 'spree/products/products-grid', products: products %>
<% end %>

<% if paginated_products.respond_to?(:total_pages) %>
  <%= paginate paginated_products %>
<% end %>

app/views/spree/products/index.html.erb
<div class="products">
  <aside>
    <% if "spree/products" == params[:controller] && @taxon %>
      <%= render 'spree/shared/search/filters', taxon: @taxon %>
    <% else %>
      <%= render 'spree/shared/navigation/taxonomies', taxon: @taxon %>
    <% end %>
  </aside>
  <section class="products_section">
    <% if params[:keywords] %>
      <% if @products.empty? %>
        <h6>
          <%= t('spree.no_products_found') %>
        </h6>
      <% else %>
        <%= render 'products', products: @products, taxon: @taxon %>
      <% end %>
    <% else %>
      <%= render 'products', products: @products, taxon: @taxon %>
    <% end %>
  </section>
</div>